{% set name = "hnswlib" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/nmslib/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: dd48bb8df3253c2c90f3c4b9c291bfae30d89bbe60383eea7a0498c3753812e5

build:
  number: 1
  skip: True  # [win or py27]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools >=42
    - pybind11 >=2.0
    - numpy >=1.10.0
  run:
    - python

test:
  imports:
    - hnswlib

about:
  home: https://github.com/nmslib/hnswlib
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Python bindings for Hnswlib, a fast approximate nearest neighbor search package.'
  dev_url: https://github.com/nmslib/hnswlib

extra:
  recipe-maintainers:
    - yihming
    - bli25broad
    - yurymalkov
